単語を追加
actlaboratory/HISS-dictionary pull request #44
Opened 2022-09-11 04:15 UTC by riku22

8単語ほど追加しました。

2022-09-11 07:11 UTC, yamahubuki commented on main.csv
> +白飯,ハクハン,4
個人的にはこれは「しろめし」だとおもっているので、なしにしたい感。
catに任せます。

2022-09-11 13:06 UTC, yncat requested changes
コメントしました

2022-09-11 13:06 UTC, yncat commented on main.csv
> +mineo,マイ’ネオ,4
これはアクセントなしでお願いします

2022-09-11 13:06 UTC, yncat commented on main.csv
> +白飯,ハクハン,4
これは読み方を断定するとまずいので削除でお願いします

2022-09-11 13:10 UTC, riku22 commented
直しました。

2022-09-12 00:03 UTC, yncat approved these changes
ありがとうございます、LGTM!

2022-09-12 00:04 UTC, merged