Add accelerate and tiers
actlaboratory/HISS-dictionary pull request #48
Opened 2022-09-14 13:44 UTC by riku22

タイトルの通りです。
別々になってしまって申し訳ないです。

2022-09-14 13:49 UTC, yncat requested changes
1個だけ

2022-09-14 13:49 UTC, yncat commented on main.csv
> +accelerate,アクセレレ’ート,4
たしかにprotalker風にするならこうなるのですが、「アクセラレート」が正しそうなのでそっちでお願いします

2022-09-14 13:58 UTC, riku22 commented on main.csv
> +accelerate,アクセレレ’ート,4
eSpeak は、アクセレレートと読んでる気がするので、こっちにしてみたんですが、とりあえず、直してみます。

2022-09-14 21:03 UTC, riku22 commented on main.csv
> +accelerate,アクセレレ’ート,4
直しました。
すみません、ほかにもいくつか追加しています。

2022-09-15 03:49 UTC, yncat approved these changes
ありがとうございます
このあたり、日本語の発音にはそもそも存在しないので、難しいんですよね。
ひとまずHISSではこちらの方針を採るということでお願いします。
LGTM

2022-09-15 03:50 UTC, merged